Repository yesiamrajeev/Hacktoberfest2025-Portfolio, pull requests merged in 2025-10, with the labels that each got.

#13 Add Krishna Saxena to contributors list
  contributors.json
Labels: hacktoberfest2025, hacktoberfest2025-accepted

#23 Added Flask logo to empty image file
  imgproject/FlaskLogo.jpeg
  index.html
Labels: hacktoberfest2025, hacktoberfest2025-accepted

#25 Add Sakshi Soni as a contributor in contributors.json
  contributors.json
  index1.css
  index1.html
Labels: hacktoberfest2025, hacktoberfest2025-accepted

#45 chore: add MIT license
  LICENSE
  contributors.json
Labels: hacktoberfest2025, hacktoberfest2025-accepted

#59 Enhance portfolio with improved animations, error handling, and form validation
  README.md
  animations.js
  contributors.json
  enhanced-styles.css
  errorHandler.js
  form-animations.js
  index.css
  index.html
  index.js
  package-lock.json
Labels: hacktoberfest2025, hacktoberfest2025-accepted

#61 Firebase config with new credentials
  index.html
Labels: hacktoberfest2025, hacktoberfest2025-accepted

#66 Added myself (Ambuj) to contributors.json
  contributors.json
Labels: hacktoberfest2025, hacktoberfest2025-accepted

#56 fix: removed placeholder text "Your Image"
  contributors.json
  index.html
Labels: hacktoberfest2025, hacktoberfest2025-accepted

#69 #issue-48 Refactor CSS for improved readability and consistency
  contributors.json
  index.css
  index1.css
Labels: hacktoberfest2025, hacktoberfest2025-accepted

#70 Update contributors.json
  contributors.json
Labels: hacktoberfest2025, hacktoberfest2025-accepted

#75 Fixes #60: JSON added
  contributors.json
Labels: hacktoberfest2025

#78 Solved Issues in enhancements.js and index.html, also enhanced .gitignore
  .gitignore
  contributors.json
  enhancements.js
  index.html
Labels: hacktoberfest2025, hacktoberfest2025-accepted

#83 Update CONTRIBUTING.md for Hacktoberfest 2025
  CONTRIBUTING.md
Labels: hacktoberfest2025, hacktoberfest2025-accepted

#87 fixed alignment of contact page
  index.css
  index.html
Labels: hacktoberfest2025, hacktoberfest2025-accepted

#93 Update contributors.json
  contributors.json
Labels: hacktoberfest2025

#99 Refine personal description in index.html
  index.html
Labels: hacktoberfest2025, hacktoberfest-accepted
